//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botty.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int id { get; set; }
        public string CommandName { get; set; }
        public string CommandDesc { get; set; }
        public string type { get; set; }
    }
}
