//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botty.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Qnum { get; set; }
        public string UserVoted { get; set; }
        public string Q { get; set; }
        public string IsActive { get; set; }
    }
}
